### ISSUE TITLE
Encryption!!!

### ISSUE THREAD

**Issue by GamerClassN7** [GamerClassN7/HA_Desktop_Companion#11]

**Comment by edwardtfn** [comment]
I saw you already have this on your plans, but I think you should prioritise at least some of the more vulnerable points. I'm OK about my laptop talking to HA unencrypted while I'm on my home network, but not with keys being stored/recorded without any encryption. I would suggest you just remove the keys from log files for now...

So, my priority order will be:

1. Remove any instance of Token being saved on the logs
2. Add HTTPS support (it should support both HTTP and HTTPS with an option to switch between internal and external networks, just like in the iOS and Android apps).

**Comment by GamerClassN7** [comment]
> I saw you already have this on your plans, but I think you should prioritise at least some of the more vulnerable points. I'm OK about my laptop talking to HA unencrypted while I'm on my home network, but not with keys being stored/recorded without any encryption. I would suggest you just remove the keys from log files for now...
> 
> So, my priority order will be:
> 
> 1. Remove any instance of Token being saved on the logs
> 2. Add HTTPS support (it should support both HTTP and HTTPS with an option to switch between internal and external networks, just like in the iOS and Android apps).

It already supports https I am running on HTTPS my self
encryption is meant usage of encryption algorithm on top of https like suggested in DOCS

**Comment by GamerClassN7** [comment]
Did you tried SSL ?

**Comment by GamerClassN7** [comment]
no response & http is supported closing
