### ISSUE TITLE
Add link to the installer in the documentation

### ISSUE THREAD

**Issue by edwardtfn** [GamerClassN7/HA_Desktop_Companion#12]
In overall, the process to start using looks OK, but I struggled on finding the EXE file (or the ZIP file containing that). I think you should always keep the latest release on the root of your repository, in order to make clear to people the download link. (Maybe that link should also be on the instructions when you mention the file name).

So, my suggestions are:

1. Add the ZIP file (latest release built) to the root of the repository, so users will be able to easily find in the list (currently only the source code is there).
2. On the installations steps, on item 2, where the name of the file is listed (HA_Desktop_Companion.exe), add a link to the ZIP file (latest release), so users can directly click into that link instead of looking around to find the file.
3. (not needed if 1 and 2 are implemented9 Add some information in the docs on how to find the files under Releases \ Assets

![image](https://user-images.githubusercontent.com/94725493/186385398-51b15f48-960f-4b04-8dcf-52e5d8480bce.png)

**Comment by GamerClassN7** [comment]
Done
