### ISSUE TITLE
Run as a Windows service

### ISSUE THREAD

**Issue by edwardtfn** [GamerClassN7/HA_Desktop_Companion#13]
I liked the idea of being an simple application which doesn't requires admin privileges to run, however, I miss the capability to run as an Windows service (way more reliable and available even before the logon) and/or having an icon on the Windows tray, so I can stop, pause, close, change settings, etc.

So, my suggestion is to have both options, run as an Application (with an user interface) or install as a Windows service (which will require admin privileges only when installing).

**Comment by GamerClassN7** [comment]
Trai icon ability to open close are already there in my eyes there is not a really need to run as service if i will implement it than in feature.

**Comment by GamerClassN7** [comment]
![image](https://user-images.githubusercontent.com/22167469/186434351-835548e4-e5de-4c22-a82e-df5a096a7dc7.png)

**Comment by edwardtfn** [comment]
Yeah, I’ve seen the icon at the tray after I wrote my message on the HA Community’s forum. That part is ok.
I still think running as a service will move this to another level. So I will insist on this.
Maybe I can contribute here. I have developed some simple services in the past and perhaps I can use that to develop a service for this tool. I will take a look.

**Comment by GamerClassN7** [comment]
Better solution Would by to split WPF Part and Service part lets fix more relevant issues before going on this journey you really don't want to be debugging RTC communication right now  👯

**Comment by GamerClassN7** [comment]
I classified it ass Enhancement so when all other more relevant issues are done it i will work on it :)

**Comment by GamerClassN7** [comment]
> 👍

In the end after rewrite and new version it is better to leave it way it is since it is less affected by user permissions
