### ISSUE TITLE
log.txt is opened in exclusive mode

### ISSUE THREAD

**Issue by edwardtfn** [GamerClassN7/HA_Desktop_Companion#17]
When starting, the application tries to open the log.txt in exclusive mode, so it will crash is the file is open in another editor (like Windows Notepad).

The application should be capable to append log entries to the file even when it is opened by other applications.

**Comment by GamerClassN7** [comment]
Acounted for in https://github.com/GamerClassN7/HA_Desktop_Companion/commit/b58858b7d929f0f9ac9adf1052368a6461434717
