### ISSUE TITLE
Microsoft Defender SmartScreen is preventing running the application

### ISSUE THREAD

**Issue by edwardtfn** [GamerClassN7/HA_Desktop_Companion#21]
I got this now ([Alpha-8](https://github.com/GamerClassN7/HA_Desktop_Companion/releases/tag/0.0.1-alpha-8)):

![image](https://user-images.githubusercontent.com/94725493/186665491-1e7b1102-9734-4ff1-8e40-814b8a1760d9.png)

**Comment by GamerClassN7** [comment]
Yes that is expected since Application is not signed, it was reported on forum previously by @Hellis81 Right now I cant do anything about it :( 

You can contribute to this solution if you want !

**Comment by GamerClassN7** [comment]
https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro

**Comment by GamerClassN7** [comment]
Shoulden`t be problem anymore can you test please @edwardtfn
