### ISSUE TITLE
UI: Typo on the app title

### ISSUE THREAD

**Issue by edwardtfn** [GamerClassN7/HA_Desktop_Companion#28]
![image](https://user-images.githubusercontent.com/94725493/187892172-be39da6a-a3da-49a7-ac33-29b4ac65fdad.png)

Should be HA_Desktop_Companion

**Comment by edwardtfn** [comment]
I've created a PR for this. Please let me know if this way of working helps. ;)
https://github.com/GamerClassN7/HA_Desktop_Companion/pull/29

**Comment by edwardtfn** [comment]
PR #35

**Comment by GamerClassN7** [comment]
Merged
