### ISSUE TITLE
Incorrect CPU temperature

### ISSUE THREAD

**Issue by edwardtfn** [GamerClassN7/HA_Desktop_Companion#32]
I can't believe my CPU is running at 347ºC, so it looks like there is an issue when converting from 34.7ºC:

![image](https://user-images.githubusercontent.com/94725493/187924580-e46a5272-6286-4d66-aca3-de2636a11087.png)

**Comment by GamerClassN7** [comment]
because it is in K not actually in C I am implementing division configuration variable co I removed hardcoded conversion from K to C so this is expected will be fixed after changes to config class

**Comment by GamerClassN7** [comment]
![image](https://user-images.githubusercontent.com/22167469/187952190-c39f3615-3ca0-4668-bf72-43f974a61075.png)

**Comment by edwardtfn** [comment]
Ok, it makes more sense now. I was feeling that 34.7ºC was not correct also, but if we are talking about 347K, which will be around 70ºC, then it makes sense.
By the way, I don't understand how the division would help here, as the conversion should be a subtraction, not a division.

**Comment by GamerClassN7** [comment]
i want to implement general solution and most all the time you are either dividing/multiplying/subtracting/adding  to convert values in this case for example you do as following: unit in K - 273.15 = C

**Comment by edwardtfn** [comment]
In this case, in order to simplify and improve clarity, you should have only `multiplier` or `ratio`, which ill be a divider when the value is lower than 1, and `offset`. Both could be positive, negative or 0. The default value for  `ratio` should be 1 and for `offset` should be 0.

You should also define (and document) the priority between those operations. Like, `ratio` will be calculated first, and then `offset`.

By the way, you are aware that this might not solve all your needs of units conversions, right?

**Comment by GamerClassN7** [comment]
> In this case, in order to simplify and improve clarity, you should have only `multiplier` or `ratio`, which ill be a divider when the value is lower than 1, and `offset`. Both could be positive, negative or 0. The default value for  `ratio` should be 1 and for `offset` should be 0.
> 
> You should also define (and document) the priority between those operations. Like, `ratio` will be calculated first, and then `offset`.
> 
> By the way, you are aware that this might not solve all your needs of units conversions, right?

Not all but most i need and it is good start 😃

**Comment by GamerClassN7** [comment]
don't forgot to delete your local configuration.yaml before testing it need to generate new one with filters in place

**Comment by GamerClassN7** [comment]
@edwardtfn did you had time ?

**Comment by edwardtfn** [comment]
I've tested, but still getting incorrect values for CPU Temperature:
![image](https://user-images.githubusercontent.com/94725493/189311346-0b4a7c05-74f7-4faf-a61a-b93c46d09734.png)


Here is some of the output:
`API/SEND/BODY
{"data":[{"unique_id":"free_ram","type":"sensor","state":2696540,"icon":"mdi:clock"},{"unique_id":"cpu_temp","type":"sensor","state":350,"icon":"mdi:cpu-64-bit"},{"unique_id":"cpu_usage","type":"sensor","state":"63","icon":"mdi:cpu-64-bit"}],"type":"update_sensor_states"}
API/RESPONSE/CODE/OK[200]
API/RESPONSE/BODY
"{\"free_ram\": {\"success\": true}, \"cpu_temp\": {\"success\": true}, \"cpu_usage\": {\"success\": true}}"
MAIN/SYNCER/TICK/5
API/ADD/SKIP/SAME/[uptime]'44'=='44'
API/ADD/SKIP/SAME/[location_in_use]'True'=='True'
API/ADD/SKIP/SAME/[microphone_in_use]'False'=='False'
API/ADD/SKIP/SAME/[currently_active_window]'HA_Desktop_Companion'=='HA_Desktop_Companion'
API/ADD/SKIP/SAME/[camera_in_use]'False'=='False'
API/ADD/SKIP/SAME/[battery_level]'97'=='97'
API/ADD/SKIP/SAME/[battery_state]'Fully Charged'=='Fully Charged'
API/ADD/DATA[free_ram]='2849696'
API/ADD/DATA[cpu_temp]='350'      ##### This is the same value I see on Home Assistant, without any transformation. #####
API/ADD/SKIP/SAME/[is_charging]'True'=='True'
API/ADD/SKIP/SAME/[wifi_ssid]'MyWiFiNetwork'=='MyWiFiNetwork'
API/ADD/SKIP/SAME/[wifi_state]'connected'=='connected'
API/ADD/DATA[cpu_usage]='46'
SENSOR/READ/True (12x)
API/SEND/BODY
{"data":[{"unique_id":"free_ram","type":"sensor","state":2849696,"icon":"mdi:clock"},{"unique_id":"cpu_temp","type":"sensor","state":350,"icon":"mdi:cpu-64-bit"},{"unique_id":"cpu_usage","type":"sensor","state":"46","icon":"mdi:cpu-64-bit"}],"type":"update_sensor_states"}
API/RESPONSE/CODE/OK[200]
API/RESPONSE/BODY`

**Comment by GamerClassN7** [comment]
that is not possible ! are you on correct branch ? @edwardtfn

**Comment by GamerClassN7** [comment]
you need to be on special branch [basic_filters](https://github.com/GamerClassN7/HA_Desktop_Companion/tree/basic_filters)

**Comment by GamerClassN7** [comment]
also pls post your configuration file

**Comment by GamerClassN7** [comment]
you need to have this undet temperature senzor definition    

 filters:
      - deduct: 273.15

**Comment by edwardtfn** [comment]
Well, Visual Studio says I'm using basic_filters, but I don't see - deduct on my configuration.yaml file (and yes, I've deleted it before running).

Let me clean up everything and try again. I come back soon.

**Comment by edwardtfn** [comment]
It was my fault... now I'm using the right branch.

So, CPU Temperature is looking good now:
![image](https://user-images.githubusercontent.com/94725493/189315267-56286f21-c884-47d2-8910-fb1ebe8329d9.png)

But as you can see, now I'm missing a bunch of other sensors... was that expected?

**Comment by GamerClassN7** [comment]
yeah i have some bugs to resolve in parser

**Comment by GamerClassN7** [comment]
thanks to @Imendin  we have fix for bug can you test it again ?

**Comment by edwardtfn** [comment]
All the sensors are there now:

![image](https://user-images.githubusercontent.com/94725493/189461110-187e9381-7c9b-4c80-b21e-28b643c1393a.png)

**Comment by GamerClassN7** [comment]
I vill make mr and then make nev version :)
