### ISSUE TITLE
Incorrect Battery status

### ISSUE THREAD

**Issue by edwardtfn** [GamerClassN7/HA_Desktop_Companion#33]
Battery state says "On AC" when it is disconnected from power.

![image](https://user-images.githubusercontent.com/94725493/187926714-d6f6629d-d2c7-479b-b161-b515f2b571b8.png)

**Comment by GamerClassN7** [comment]
Interesting can you please provide Model number and manufacturer of your laptop ?

**Comment by edwardtfn** [comment]
I'm using a HP EliteBook x360 1030 G4.
When I disconnect the power cable the value of BatteryStatus under Win32_Battery changes from 2 to 1, s probably there is an offset when compared to your computer.
This is probably why I'm also having "Fully charged" when it is still charging:
![image](https://user-images.githubusercontent.com/94725493/187980299-32b52619-4a0d-42ca-ae1f-ccfba84a5fc6.png)

**Comment by GamerClassN7** [comment]
Be aware that HP have special Feature's in place to protect battery  do my computer is most off time running on AC to protect battery and Battey is left somewhere between 98-100% I also have an laptop any suggestion how to fix this issue ?

**Comment by GamerClassN7** [comment]
Also when you are connected to main and battery is ower 98% hp marks battery as fully charged  it is same on my site but  that is some times stuck on ac and than even that it is unplugged its still there is weird

**Comment by GamerClassN7** [comment]
@edwardtfn could you investigate thinks mentioned up if thy apply ?

**Comment by edwardtfn** [comment]
Sure! Will put some time on this later this week.

Anyway, there's the documentation from Microsoft: https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-battery and based on that the currently status reported by the application is correct, so it might be something on my laptop.

I will take a look.

**Comment by GamerClassN7** [comment]
ani information we can try to use ?

**Comment by GamerClassN7** [comment]
Reminder :) @edwardtfn

**Comment by Hellis81** [comment]
You can change the order in configuration.yaml. 

On my computer the correct order seems to be:

```
  - platform: wmic
    wmic_path: Win32_Battery
    wmic_selector: BatteryStatus
    wmic_namespace: \\root\CIMV2
    value_map: "Fully Charged|Discharging|On AC|Low|Critical|Charging|Charging and High|Charging and Low|Undefined|Partially Charged"
    name: Battery State
    unique_id: battery_state
    icon: "mdi:battery-minus"
    entity_category: "diagnostic"
    device_class: battery
```
At least the first three states, I have never tried to force the other

**Comment by GamerClassN7** [comment]
> You can change the order in configuration.yaml.
> 
> On my computer the correct order seems to be:
> 
> ```
>   - platform: wmic
>     wmic_path: Win32_Battery
>     wmic_selector: BatteryStatus
>     wmic_namespace: \\root\CIMV2
>     value_map: "Fully Charged|Discharging|On AC|Low|Critical|Charging|Charging and High|Charging and Low|Undefined|Partially Charged"
>     name: Battery State
>     unique_id: battery_state
>     icon: "mdi:battery-minus"
>     entity_category: "diagnostic"
>     device_class: battery
> ```
> 
> At least the first three states, I have never tried to force the other.
> 
> EDIT.. I see now that might not have been the issue. Perhaps make the is charging entity the same way as battery status so we can change the order depending on how the computer reports it?

You can map_value: attribute is common for all non binary sensors same with filters and decimal filter ;)

**Comment by GamerClassN7** [comment]
also by this officinal documentation page all values should be same across the spectrum i vill try to look in to value mapper tomorrow maybe problem is there

https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-battery

**Comment by GamerClassN7** [comment]
Addressed in new version
