### ISSUE TITLE
Location is not fetched from ipinfo

### ISSUE THREAD

**Issue by Hellis81** [GamerClassN7/HA_Desktop_Companion#45]
I looked through the code and found this part here in sensors.cs

```
        public static string queryLocationByIP()
        {
            try
            {
                string info = new WebClient().DownloadString("http://ipinfo.io/");
                return (string) JsonSerializer.Deserialize<JsonObject>(info)["loc"];
            }
            catch (Exception)
            {
                return null;
            }
        }
```

When I inspect the element I get this path:
`#loc-string > div > span > span:nth-child(2) > span`

Is that what should be used where it says ["loc"]?

**Comment by GamerClassN7** [comment]
no it is because `JsonSerializer.Deserialize` which omit all html and leave only json  how ever i think i disable this feature for now because it vas not available in yaml conf and i was not happy to release it when users dont have control on on/of of this feature next release should have it

**Comment by GamerClassN7** [comment]
Addressed in new version
