### ISSUE TITLE
Limit the size of the log file

### ISSUE THREAD

**Issue by Hellis81** [GamerClassN7/HA_Desktop_Companion#65]
I just noticed that my work computer had low storage. I know it's bad but when Windows noted me that I had less than 100 MB it was kind of shocking.
I found the reason ;-)

![image](https://github.com/GamerClassN7/HA_Desktop_Companion/assets/61010215/ae37fff1-3fa5-4828-8e28-9971537d8984)

**Comment by GamerClassN7** [comment]
Good point ;) added to Todo Sorry for problems

**Comment by GamerClassN7** [comment]
As a temporary mitigation just delete log file and restart the app

**Comment by GamerClassN7** [comment]
@Hellis81  alteady started vorkin on fix https://github.com/GamerClassN7/HA_Desktop_Companion/pull/66

**Comment by Hellis81** [comment]
Great!! 
Thank you
