### ISSUE TITLE
HA_icon.ico missing

### ISSUE THREAD

**Issue by SideTrackedResearch** [GamerClassN7/HA_Desktop_Companion#70]
HA_icon.ico seems to be missing from HA_Self_Contained.zip file after unzipping and not allowing the program to execute. I unzipped the file into a folder "HAComp" on my c drive. 

The Log reads
**[03/12/2024-20:22:24][0]Initialization
[03/12/2024-20:22:24][3][HA]Could not find file 'C:\HAcomp\ha_logo.ico'**

And that is all it contained.

I downloaded the icon from the github page, added to the unzipped file, and the program launched.

**Comment by GamerClassN7** [comment]
Sorry for Problems i reuploded latest relase!

**Comment by SideTrackedResearch** [comment]
Thanks! Keep up the good work.
