### ISSUE TITLE
Not all sensors are there

### ISSUE THREAD

**Issue by OsaedYahya** [GamerClassN7/HA_Desktop_Companion#72]
First off thank you for this great companion app!
It's amazing and it's working better than I would've dreamt of
However as from what I've seen there are more sensors that my PC isn't giving out. is it a permissions issue from my end or what might cause this?

<img width="331" alt="image" src="https://github.com/GamerClassN7/HA_Desktop_Companion/assets/69788216/b87d8a2b-28fe-419e-9bea-dd43bf5ed88d">

**Comment by GamerClassN7** [comment]
> st off thank you for this great companion app!
> It's amazing and it's working better than I would've dreamt of
> However as from what I've seen there are more sensors that my PC isn't giving out. is it a permissions issue from m

Hello first thank you for Using my Crappy App
Could i ask you to post your configuration.yaml ?

**Comment by GamerClassN7** [comment]
> > st off thank you for this great companion app!
> > It's amazing and it's working better than I would've dreamt of
> > However as from what I've seen there are more sensors that my PC isn't giving out. is it a permissions issue from m
> 
> Hello first thank you for Using my Crappy App
> Could i ask you to post your configuration.yaml ?

@OsaedYahya  ?

**Comment by GamerClassN7** [comment]
@OsaedYahya  no response closing feel free to reopen issue again
