### ISSUE TITLE
Audio is not playing from notifications

### ISSUE THREAD

**Issue by OsaedYahya** [GamerClassN7/HA_Desktop_Companion#73]
I started using your companion app today and I am fiddling around with it
I really like the image notifications but I couldn't run the audio notifications.

(In your example you're using a png :P )
Can you please provide a working example to test it out?

**Comment by GamerClassN7** [comment]
> I started using your companion app today and I am fiddling around with it I really like the image notifications but I couldn't run the audio notifications.
> 
> (In your example you're using a png :P ) Can you please provide a working example to test it out?

I will try to add example to  README today when i have some time

**Comment by GamerClassN7** [comment]
Ohh... HI once more just add url for wav file and it should work JSON is correct only url is bad :)
