### ISSUE TITLE
sensor entities all have "debug" in the name

### ISSUE THREAD

**Issue by bbrendon** [GamerClassN7/HA_Desktop_Companion#78]
I just installed this yesterday.  They are all named : sensor.debug_*

**Comment by GamerClassN7** [comment]
> I just installed this yesterday. They are all named : sensor.debug_*

Hello. first thanks for coosing my app !!! :)

Can you please post your configuration.yaml  ?

**Comment by GamerClassN7** [comment]
Closing due to no response user probably left debug flag in configuration.yaml which is enabled by default
