### ISSUE TITLE
[FEATURE] Entity/Sensor selection menu

### ISSUE THREAD

**Issue by Yotie2000** [GamerClassN7/HA_Desktop_Companion#87]
It would be great to habe a menu in which you can select which entities/sensors to create. 
For example on my PC the location doesnt make sense since its always at the same place and it doesnt have a battery.

**Comment by GamerClassN7** [comment]
> It would be great to habe a menu in which you can select which entities/sensors to create. 
> For example on my PC the location doesnt make sense since its always at the same place and it doesnt have a battery.


Hello you can do this already, just edit your configuration.yaml and remove sensors you don't like/want no menu necessary ;)

EDIT: I really want to leave my app as simple as it can be, so it can be well tuned :) how ever if you want you can make contribution to code :) I always welcome another contributor.
